# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884727924890c06e3fd1e5affbe3363f14a504957c62a9b6e2f8474ab35082253ba3463a299f42e36aec39f2f421ee3cd66683ddc770b371abe9214f41751fea

test:
  secret_key_base: 81cab700f3cac525f0738aba9dc457768c307f310acc9bf951b808b5381fbecf4658b6a2442272ca53cdc88c35dcb7b1c83564f9d6520e0184d94e9afecc00de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
